In [44]:
#Imports
import os
import numpy as np
import pandas as pd

In [45]:
#Get The directory and assaign file
os.getcwd()
os.chdir('C:\\Users\shaqu\Desktop\datavis\ca1\DataVisualisationCA1') 
data = 'sharktank.csv'

In [46]:
#Put data into pandas DataFrame and display , encoding changed otherwise the file does not read correctly. 
sharktank = pd.read_csv(data,encoding='ISO-8859-1')
sharktank.head()

,Season Number,Episode Number,Pitch Number,Startup Name,Industry,Business Description,Pitchers Gender,Pitchers State,Pitchers City,Entrepreneur Names,...,Guest Investment Amount,BarbaraCorcoran Present,MarkCuban Present,LoriGreiner Present,RobertHerjavec Present,DaymondJohn Present,KevinOLeary Present,KevinHarrington Present,Guest Name,Notes
0,1,1,1,AvaTheElephant,Health / Wellness,Ava The Elephant - Baby and Child Care,Female,GA,Atlanta,Tiffany Krumins,...,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN
1,1,1,2,Mr.Tod'sPieFactory,Food and Beverage,Mr. Tod's Pie Factory - Specialty Food,Male,NJ,Somerset,Tod Wilson,...,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN
2,1,1,3,Wispots,Business Services,Wispots - Consumer Services,Male,NC,Cary,Kevin Flannery,...,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN
3,1,1,4,CollegeFoxesPackingBoxes,Lifestyle / Home,College Foxes Packing Boxes - Consumer Services,Male,FL,Tampa,"Nick Friedman, Omar Soliman",...,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN
4,1,1,5,IonicEar,Software / Tech,Ionic Ear - Novelties,Male,MN,St. Paul,Darrin Johnson,...,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN

In [47]:
#As Discussed with Ajay, replacing the files empty cells with 0's
sharktank.replace(np.nan, 0, inplace = True)

In [48]:
#As of season 7 we lose pitcher information and some select company websites also contain empty cells
#We replace those 0's with 'N/A' to ensure the columns remain as containing only strings.
sharktank['Pitchers State'] = sharktank['Pitchers State'].astype(str) 
sharktank['Pitchers State'].replace(str(0),'N/A', inplace = True)

sharktank['Pitchers City'] = sharktank['Pitchers City'].astype(str) 
sharktank['Pitchers City'].replace(str(0),'N/A', inplace = True)

sharktank['Entrepreneur Names'] = sharktank['Entrepreneur Names'].astype(str) 
sharktank['Entrepreneur Names'].replace(str(0),'N/A', inplace = True)

sharktank['Company Website'] = sharktank['Company Website'].astype(str) 
sharktank['Company Website'].replace(str(0),'N/A', inplace = True)

In [49]:
sharktank

,Season Number,Episode Number,Pitch Number,Startup Name,Industry,Business Description,Pitchers Gender,Pitchers State,Pitchers City,Entrepreneur Names,...,Guest Investment Amount,BarbaraCorcoran Present,MarkCuban Present,LoriGreiner Present,RobertHerjavec Present,DaymondJohn Present,KevinOLeary Present,KevinHarrington Present,Guest Name,Notes
0,1,1,1,AvaTheElephant,Health / Wellness,Ava The Elephant - Baby and Child Care,Female,GA,Atlanta,Tiffany Krumins,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0
1,1,1,2,Mr.Tod'sPieFactory,Food and Beverage,Mr. Tod's Pie Factory - Specialty Food,Male,NJ,Somerset,Tod Wilson,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0
2,1,1,3,Wispots,Business Services,Wispots - Consumer Services,Male,NC,Cary,Kevin Flannery,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0
3,1,1,4,CollegeFoxesPackingBoxes,Lifestyle / Home,College Foxes Packing Boxes - Consumer Services,Male,FL,Tampa,"Nick Friedman, Omar Soliman",...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0
4,1,1,5,IonicEar,Software / Tech,Ionic Ear - Novelties,Male,MN,St. Paul,Darrin Johnson,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,11,23,987,RescueReady,Lifestyle/Home,Rescue Ready -,Male,N/A,N/A,N/A,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
987,11,24,988,YellowLeafHammocks,Fitness/Sports/Outdoors,Yellow Leaf Hammocks -,Mixed Team,N/A,N/A,N/A,...,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
988,11,24,989,DreamlandBaby,Children/Education,Dreamland Baby -,Female,N/A,N/A,N/A,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
989,11,24,990,RollinGreens,Food and Beverage,RollinGreens -,Mixed Team,N/A,N/A,N/A,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
990,11,24,991,TheMadOptimist,Health/Wellness,The Mad Optimist -,Male,N/A,N/A,N/A,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [50]:
sharktank.to_csv('SharkTankV1.csv', index = False)